### ISSUE TITLE
[Refactor] 

### ISSUE THREAD

**Issue by hyeonjeongs** [KINGSAMJO/Server_Hyeonjeong#7]
## 📌  Feature Issue
해보고 싶은 것들 적용하기

## 📝  To-do

- [x] 코루틴으로 서버 IO thread에서 비동기 처리
- [x] viewModel 적용
- [x] 깃허브 API 연동
- [x] diffUtil 사용
- [x] 서버 통신 후 데이터 불러오는거 느린 문제 해결
